#!/bin/sh

set -e

# Including common functions
. "${LB_BASE:-/usr/share/live/build}"/scripts/build.sh

# Setting static variables
# shellcheck disable=SC2034
{
    DESCRIPTION="$(Echo 'add isolinux files')"
    HELP=""
    USAGE="${PROGRAM}"
}

# Reading configuration files
Read_conffiles config/all config/bootstrap config/common config/binary
Set_defaults

[ "${LB_ARCHITECTURE}" = amd64 ] || exit 0

# Seems like we'll have work to do
Echo_message "add isolinux files"

mkdir -p binary/isolinux

cat <<EOF >binary/isolinux/sorry32.txt



We are sorry!

Tails can not work on this computer:
Tails now requires a 64-bit computer.

For more information, see:
https://tails.net/doc/about/requirements/



EOF
