#!/usr/bin/python3 -I

# In order to implement the desired "open Passwords.kdbx by default"
# behavior, a much simpler "if no command line argument is passed to
# the wrapper and ~/Persistent/Passwords.kdbx exists, then run exec
# /usr/bin/secrets ~/Persistent/Passwords.kdbx" would be sufficient.
# This could be implemented directly in the /usr/local/bin/secrets
# wrapper. It would work just fine for the users who use only
# 1 database and have adopted our defaults (either initially, or
# accepted the automated migration that we've been offering).
#
# What this script adds, on top of this, is primarily that it makes
# life a little bit easier for:
#
#  - users who chose to give their password database file a different
#    name, while still saving it at the root of ~/Persistent/ (as
#    opposed to any other persistent folder)
#
#  - users who use multiple password databases, all stored at the root
#    of ~/Persistent/ (as opposed to any other persistent folder)
#
# To take benefit of this, these users need to click the ⬇️ button on
# the right of the Open button, to see the list of "Recent Files".
#
# Additionally, this script satisfies the wishes of users who use at
# least 2 password databases, including ~/Persistent/Passwords.kdbx,
# and want the last opened database to be opened by default next time
# they start Secrets.

import logging
import sys
from pathlib import Path

import gi

gi.require_version("Gio", "2.0")
gi.require_version("GLib", "2.0")
from gi.repository import Gio, GLib  # noqa: E402

PERSISTENT_DIR = Path("~/Persistent").expanduser()

secrets_settings = Gio.Settings(schema="org.gnome.World.Secrets")


def path_to_uri(p: Path) -> str:
    return f"file://{p.absolute()}"


def get_default_database(files: list[Path]) -> Path | None:
    choices = ["Passwords.kdbx"]
    for c in choices:
        for f in files:
            if f.name == c:
                return f

    if len(files) == 1:
        return files[0]

    return None


def main() -> int:
    logging.basicConfig(level=logging.INFO)
    kdbx_files = list(PERSISTENT_DIR.glob("*.kdbx"))
    current_list = list(secrets_settings.get_value("last-opened-list"))

    if current_list:
        logging.debug("No need to do anything: dconf has already been set")
        return 0

    for kdbx in kdbx_files:
        uri = path_to_uri(kdbx)
        if uri not in current_list:
            current_list.append(uri)

    errors = False

    logging.info("%d kdbx files found", len(current_list))
    if not secrets_settings.set_value(
        "last-opened-list", GLib.Variant.new_strv(current_list)
    ):
        logging.error("Could not set last-opened-list")
        errors = True
    default_database = get_default_database(kdbx_files)
    if default_database:
        logging.info("Setting a default database: %s", default_database)
        if not secrets_settings.set_value(
            "last-opened-database",
            GLib.Variant.new_string(path_to_uri(default_database)),
        ):
            logging.error("Could not set last-opened-database")
            errors = True

    secrets_settings.sync()

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
