# This CI is largely copy-pasta from tor's CI. Basically we want to ensure
# that changes to chutney don't break tor's CI.
#
# TODO: Modularize this further and move to a common location where the tor CI
# can use it too?

spec:
  inputs:
    tor-repo:
      description: Which tor repo to test against
    tor-branch:
      description: Which branch of tor-repo to test against
    tor-commit:
      description: Which commit on tor-branch to test against

# end [header](https://docs.gitlab.com/ee/ci/yaml/#header-keywords)
---
    
# This template is for exporting ephemeral things from the scripts.  By
# convention we expect our scripts to copy stuff into artifacts/, rather than
# having a big list of files that be treated as artifacts.
.tor-artifacts-template: &tor-artifacts-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 week
    when: always
    paths:
      - artifacts/

# This template is used for x86-64 builds.
.tor-x86-64-template: &tor-x86-64-template
  tags:
    - amd64

# This template should be usable on any system that's based on apt.
.tor-apt-template: &tor-apt-template |
      export LC_ALL=C.UTF-8
      echo Etc/UTC > /etc/timezone
      mkdir -p apt-cache
      export APT_CACHE_DIR="$(pwd)/apt-cache"
      rm -f /etc/apt/apt.conf.d/docker-clean
      echo 'quiet "1";' \
           'Acquire::Retries "20";' \
           'APT::Install-Recommends "0";' \
           'APT::Install-Suggests "0";' \
           'APT::Get::Assume-Yes "true";' \
           'Dpkg::Use-Pty "0";' \
           "Dir::Cache::Archives \"${APT_CACHE_DIR}\"; " \
        >> /etc/apt/apt.conf.d/99gitlab
      apt-get update -qq
      apt-get upgrade -qy

# This template sets us up for Debian system in particular.
.tor-debian-template: &tor-debian-template
  <<: *tor-artifacts-template
  <<: *tor-x86-64-template
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  # TODO: Using "cache" in this way speeds up our downloads.  It would be
  # even better, though, to start with a pre-upgraded debian image.
  #
  # TODO: Will we have to do this differently once we have more than one
  # debian version that we're using?
  cache:
    key: apt
    paths:
      - apt-cache
  before_script:
    - *tor-apt-template
    - mkdir artifacts
    # Install patches unconditionally.
    - apt-get install
        apt-utils
        automake
        build-essential
        ca-certificates
        file
        git
        libevent-dev
        liblzma-dev
        libscrypt-dev
        libseccomp-dev
        libssl-dev
        pkg-config
        python3
        zlib1g-dev
    # Install patches that we only need for some use cases.
    - if [ "$ASCIIDOC" = yes ]; then apt-get install asciidoc xmlto; fi
    - if [ "$DOXYGEN" = yes ]; then apt-get install doxygen; fi
    - if [ "$STEM" = yes ]; then apt-get install timelimit; fi
    - if [ "$CC" = clang ]; then apt-get install clang; fi
    - if [ "$NSS" = yes ]; then apt-get install libnss3 libnss3-dev; fi
    # llvm-symbolizer for sanitizer backtrace
    - if [ "$HARDENING" = yes ]; then apt-get install llvm; fi
    # libubsan1 for building with -fsanitize=address
    - if [ "$HARDENING" = yes ]; then apt-get install libubsan1 libclang-rt-dev; fi
    # TODO: This next line should not be debian-only.
    - if [ "$STEM" = yes ]; then git clone --depth 1 https://gitlab.torproject.org/tpo/network-health/stem.git ; export STEM_PATH="$(pwd)/stem"; fi
    # TODO: This next line should not be debian-only.
    # Unlike tor's CI pipeline, we want to use chutney from *this branch*
    - export CHUTNEY_PATH="$CI_PROJECT_DIR"
    # Install chutney to get its dependencies.
    - apt install python3-venv
    - python3 -m venv venv
    - venv/bin/pip install .
    - if [ "$TRACING" = yes ]; then apt install liblttng-ust-dev; fi

tor-debian-integration:
  image: containers.torproject.org/tpo/tpa/base-images/debian:bookworm
  <<: *tor-debian-template
  variables:
    CHECK: "no"
    CHUTNEY: "yes"
    CHUTNEY_MAKE_TARGET: "test-network-all"
    STEM: "no"
    ALL_BUGS_ARE_FATAL: "yes"
  script:
    - source venv/bin/activate
    - mkdir ~/src
    - git clone --shallow-since=2024-01-01 -b $[[ inputs.tor-branch ]] $[[ inputs.tor-repo ]] ~/src/tor
    - cd ~/src/tor
    - git checkout $[[ inputs.tor-commit ]]
    - ./scripts/ci/ci-driver.sh
