#!/bin/sh

set -e
set -u

# Remove pidgin's (libpurple's) support for protocols we don't support.

echo "Removing Pidgin libraries for protocols we do not support"

. /usr/share/tails/build/variables

if [ "${LB_ARCHITECTURE}" = amd64 ]; then
   GNU_TRIPLET="x86_64-linux-gnu"
else
   GNU_TRIPLET="aarch64-linux-gnu"
fi

KEEP="irc|jabber|xmpp"

find "/usr/lib/${GNU_TRIPLET}/purple-2/" -name 'lib*.so' \
   | /bin/grep -Ev "/lib($KEEP)\.so" \
   | xargs rm
