workflow:
  rules:
    # Explicitly opt into merge request pipelines.
    # This in turn enables gitlab CI variables that are only
    # set on merge request pipelines (as opposed to the default "push" trigger),
    # such as CI_MERGE_REQUEST_DIFF_BASE_SHA.
    # https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html#add-jobs-to-merge-request-pipelines
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Also run on pushes to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# These variables are set everywhere, unconditionally.
variables:
  TERM: "ansi"
  DEBUG_CI: "yes"

include:
  # Run our clone of tor's CI
  - local: ci/tor-gitlab-ci.yml
    inputs:
      tor-repo: https://gitlab.torproject.org/tpo/core/tor.git
      tor-branch: main
      # main@2026-01-26
      tor-commit: 3a7bb70e0141c109c14337a0fc3c0ba7d9632119
  - project: tpo/tpa/ci-templates
    file: scripts/apt.yml
    # main@2026-01-26
    ref: b521e40f68f5e6e262f702a4bd1496f0a665655d

# A more stripped-down debian template for tests that aren't specifically
# replicating tor's CI.
.debian-template: &debian-template
  image: containers.torproject.org/tpo/tpa/base-images/debian:bookworm
  tags:
    - amd64
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    # Number of seconds to allow for bootstrap, overriding the default of 60.
    # 120 is what e.g. bootstrap-network.sh uses.
    # Give even a bit more than that since we're not using retries (as test-network.sh does)
    CHUTNEY_START_TIME: 300
    # We generally want debug output, in tests running chutney
    CHUTNEY_DEBUG: 1
  cache:
    key: bookworm-$CI_JOB_NAME_SLUG-apt
    paths:
      # tpo/tpa/ci-templates's [.apt-init] puts the apt cache here
      - .cache/apt
  before_script:
    # Defined in tpo/tpa/ci-templates
    - !reference [.apt-init]
    # We install binaries such as shadow here.
    - mkdir "$HOME"/.local
    - export PATH="$PATH:$HOME/.local/bin"
    # Create and initialize a python venv
    - apt-get install
        python3
        python3-pip
        python3-venv
    - python3 -m venv $HOME/venv
    - source $HOME/venv/bin/activate
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - net

run-examples:
  <<: *debian-template
  script:
    - apt-get install
        tor
    - python3 -m pip install .
    - ./examples/use_as_module.py

chutney-as-module-tests:
  <<: *debian-template
  script:
    - apt-get install
        tor
    - python3 -m pip install .

    # For testing ssh launcher, connecting back into the localhost container
    - apt-get install ssh
    - service ssh start
    - ssh-keygen -f ~/.ssh/id_rsa -P ""
    - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

    - ./tests/chutney-as-module-tests

# Tests the `chutney` script autogenerated by pip,
# which directly invokes TorNet.__main__
chutney-script:
  <<: *debian-template
  script:
    - apt-get install
        tor
    - python3 -m pip install .

    # Use the chutney wrapper script generated by pip.
    # It should be on the path.
    - CHUTNEY=$(type -p chutney)

    # Name of a built-in network
    - NETWORK=basic-min

    - |
      "$CHUTNEY" init --net="$NETWORK"
      "$CHUTNEY" configure
      "$CHUTNEY" start
      "$CHUTNEY" wait_for_bootstrap
      "$CHUTNEY" verify
      "$CHUTNEY" stop

unit-tests:
  <<: *debian-template
  script:
  - python3 -m pip install .
  - ./tests/unit-tests.sh

torrc-template-tests:
  <<: *debian-template
  script:
  - apt-get install
      obfs4proxy
      tor
  - python3 -m pip install .
  - ./tests/torrc-template-tests

network-config-tests:
  <<: *debian-template
  needs:
  - build-arti
  script:
  - apt-get install
      obfs4proxy
      stow
      tor
  - python3 -m pip install .
  - stow -d opt -t "$HOME"/.local arti
  - ./tests/network-config-tests

# We currently only use shadow in one job, but building it is complex enough
# that it's probably worth putting in its own job.
build-shadow:
  <<: *debian-template
  variables:
    JOB_SHADOW_REPO: "https://github.com/shadow/shadow.git"
    JOB_SHADOW_BRANCH: "main"
    # main @ 2025-12-10
    JOB_SHADOW_COMMIT: "7b2d0c526b93594e9572a9f639faccd6a715e1f4"
  artifacts:
    paths:
      - opt/shadow
      - wheels
    # Intended for consumption later in the pipeline; no need to keep them
    # around for longer.
    expire_in: 1 day
  cache:
    - key: v0-bookworm-$CI_JOB_NAME-$JOB_SHADOW_COMMIT
      paths:
      - opt/shadow
      - wheels
  tags:
    - amd64
  script:
    # Build shadow
    - |
      if [ -f opt/shadow/bin/shadow ]
      then
        echo "Using shadow binary from cache"
      else
        echo "Building shadow"
        apt-get install git
        git clone --shallow-since=2021-08-01 -b $JOB_SHADOW_BRANCH $JOB_SHADOW_REPO ~/src/shadow
        cd ~/src/shadow
        git checkout $JOB_SHADOW_COMMIT
        export CC=gcc CXX=g++ CONTAINER=debian:bookworm BUILDTYPE=release RUSTPROFILE=minimal
        ci/container_scripts/install_deps.sh
        ci/container_scripts/install_extra_deps.sh
        export PATH="$HOME/.cargo/bin:${PATH}"
        ./setup build --jobs $(nproc) --prefix $CI_PROJECT_DIR/opt/shadow
        ./setup install
        apt-get install -y python3-pip
        mkdir $CI_PROJECT_DIR/wheels
        python3 -m pip wheel --wheel-dir=$CI_PROJECT_DIR/wheels ./shadowtools
      fi

build-arti:
  <<: *debian-template
  variables:
    JOB_ARTI_REPO: "https://gitlab.torproject.org/tpo/core/arti.git"
    # This can be a tag or commit-hash.
    # main @ 2025-09-16.
    JOB_ARTI_REV: "e67444c5d417d3a527ba282eee8c18d9e1e32c2d"
    # comma-separated list of features to build with
    JOB_ARTI_FEATURES: onion-service-service,hsc,restricted-discovery
    JOB_ARTI_PROFILE: "quicktest"
    JOB_RUST_TOOLCHAIN: "1.87.0"
  artifacts:
    paths:
      - opt/arti
    # Intended for consumption later in the pipeline; no need to keep them
    # around for longer.
    expire_in: 1 day
  cache:
    - key: V1-bookworm-$CI_JOB_NAME-$JOB_ARTI_REV-$JOB_RUST_TOOLCHAIN-$JOB_ARTI_PROFILE-$JOB_ARTI_FEATURES
      paths:
      - opt/arti
  tags:
    - amd64
  script:
    - |
      set -x
      if [ -f opt/arti/bin/arti ]
      then
        echo "Using arti binary from cache"
      else
        echo "Building arti"

        # Install rust
        apt-get install git curl build-essential pkg-config libssl-dev libsqlite3-dev
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain none --profile minimal
        source "$HOME/.cargo/env"
        rustup toolchain install $JOB_RUST_TOOLCHAIN
        cargo --version

        # Build and install arti
        cargo install \
          --locked \
          --root="$CI_PROJECT_DIR"/opt/arti \
          --profile=$JOB_ARTI_PROFILE \
          --git=$JOB_ARTI_REPO \
          --rev=$JOB_ARTI_REV \
          --features=$JOB_ARTI_FEATURES \
          arti
      fi

# This runs the test-network script for some network flavors, under shadow.
# It's similar to the tor CI test, but we run under shadow for speed and
# determinism, and test a different set of networks, notably including arti networks.
shadow-test-network:
  <<: *debian-template
  needs:
  - build-shadow
  - build-arti
  tags:
    - amd64
    # Non-TPA runners may not support running shadow.
    - tpa
  script:
  - set -x
  - apt-get install
      git
      stow
      tor
      libssl3
      libsqlite3-0
      obfs4proxy
  # install shadow
  - apt-get install libglib2.0-0
  - mkdir -p "$HOME"/.local
  - stow -d opt -t "$HOME"/.local shadow
  # install shadowtools, for `shadow-exec`
  - python3 -m pip install --no-index --find-links=./wheels shadowtools
  # install chutney
  - python3 -m pip install .
  # run the test
  # TODO(arti#1986): re-add `hs-v3-arti` when it passes consistently.
  - |
    for flavor in \
          basic \
          basic-arti \
          basic-families \
          bridges-min \
          bridges-min-arti \
          bridges-obfs4 \
          ; do
      shadow-exec \
        --shadow-args="--model-unblocked-syscall-latency=true --max-unapplied-cpu-latency=10ms" \
        -- \
      bash -c \
      "
        set -x
        set -euo pipefail
        # Too noisy
        export CHUTNEY_DEBUG=0
        # Tell the "verify" test to connect to hidden services with *every*
        # client. We want this to e.g. validate cross-compatibility between tor
        # and arti clients and servers.
        export CHUTNEY_HS_MULTI_CLIENT=1
        export PATH=\"$PATH\"
        export CHUTNEY_ARTI=\"$CI_PROJECT_DIR\"/opt/arti/bin/arti
        tools/test-network.sh \
        --chutney-path \"$CI_PROJECT_DIR\" \
        --net-dir \"$CI_PROJECT_DIR\"/net/\"$flavor\" \
        --sandbox 0 \
        --no-controlsocket \
        --no-ipv6 \
        --tor \"$(which tor)\" \
        --tor-gencert \"$(which tor-gencert)\" \
        --stop-time 0 \
        --flavor \"$flavor\""
    done

  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - net

network-config-tests-diff:
  <<: *debian-template
  needs:
  - build-shadow
  - build-arti
  tags:
    - amd64
    # Non-TPA runners may not support running shadow.
    - tpa
  # This job fails if there's any diff in output. Often such a diff is expected,
  # though should be reviewed.
  allow_failure: true
  rules:
    # Only run in merge-request pipelines, where CI_MERGE_REQUEST_DIFF_BASE_SHA
    # is defined.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
  - apt-get install
      diffoscope-minimal
      git
      obfs4proxy
      stow
      tor

  # install shadow
  - apt-get install stow libglib2.0-0
  - mkdir -p "$HOME"/.local
  - stow -d opt -t "$HOME"/.local shadow

  # install shadowtools, for `shadow-exec`
  - python3 -m pip install --no-index --find-links=./wheels shadowtools

  # install arti
  - stow -d opt -t "$HOME"/.local arti

  # No need to install chutney; `network-config-tests-diff` does it itself.

  - ./tests/network-config-tests-diff "$CI_MERGE_REQUEST_DIFF_BASE_SHA"
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - artifacts

shellcheck:
  <<: *debian-template
  script:
  - apt-get install
      shellcheck
  - ./tests/shellcheck-tests.sh

python-lint:
  <<: *debian-template
  variables:
    # Most recent as of 2026-01-20
    BLACK_VERSION: 26.1.0
    # Most recent as of 2026-01-20
    MYPY_VERSION: 1.19.1
    # Most recent as of 2026-01-20
    FLAKE8_VERSION: 7.3.0
    # Most recent as of 2026-02-18
    FLAKE8_TYPE_CHECKING_VERSION: 3.1.1
  script:
  # We don't really need chutney itself installed, but we do need
  # its dependencies so that mypy can see their relevant types.
  - python3 -m pip install .

  - FAILURES=""

  - python3 -m pip install mypy=="$MYPY_VERSION"
  - python3 -m pip install types-paramiko
  - if ! mypy --exclude build . ; then FAILURES+=" mypy"; fi

  - python3 -m pip install black=="$BLACK_VERSION"
  - if ! black --check --diff . ./lib/chutney/data/networks/*; then FAILURES+=" black"; fi

  - python3 -m pip install flake8=="$FLAKE8_VERSION"
  - python3 -m pip install flake8-type-checking=="$FLAKE8_TYPE_CHECKING_VERSION"
  - if ! flake8 . ; then FAILURES+=" flake8"; fi

  - |
    if [ -n "$FAILURES" ]; then
      echo "Failed linters: $FAILURES";
      exit 1;
    fi
